### ISSUE TITLE
Resolution of references broken in DN 5.1

### ISSUE THREAD

**Issue by nonstans** [datanucleus/datanucleus-mongodb#46]
I'm currently migrating from DN core 5.0.8 to 5.1.8 and datanucleus-mongodb
5.0.4 to 5.1.0-release. I get the following exception when trying to read an object containing a reference to a sub-object:

`..
Caused by: java.lang.NullPointerException
	at org.datanucleus.store.mongodb.MongoDBUtils.getClassNameForIdentity(MongoDBUtils.java:216)
	at org.datanucleus.store.mongodb.MongoDBStoreManager.getClassNameForObjectID(MongoDBStoreManager.java:190)
	at org.datanucleus.ExecutionContextImpl.getClassNameForObjectId(ExecutionContextImpl.java:3741)
	at org.datanucleus.ExecutionContextImpl.getClassDetailsForId(ExecutionContextImpl.java:3635)
	at org.datanucleus.ExecutionContextImpl.findObject(ExecutionContextImpl.java:3502)
	at org.datanucleus.identity.IdentityUtils.getObjectFromIdString(IdentityUtils.java:474)
	at org.datanucleus.store.mongodb.fieldmanager.FetchFieldManager.getValueForContainerRelationField(FetchFieldManager.java:968)
	at org.datanucleus.store.mongodb.fieldmanager.FetchFieldManager.fetchNonEmbeddedObjectField(FetchFieldManager.java:735)
	at org.datanucleus.store.mongodb.fieldmanager.FetchFieldManager.fetchObjectField(FetchFieldManager.java:683)
	at org.datanucleus.state.StateManagerImpl.replacingObjectField(StateManagerImpl.java:1953)
	at de.mpg.ipp.codac.business.schema.teamwork.UserGroup.dnReplaceField(UserGroup.java)
	at de.mpg.ipp.codac.business.schema.common.W7XDbNamedObject.dnReplaceFields(W7XDbNamedObject.java)
	at org.datanucleus.state.StateManagerImpl.replaceFields(StateManagerImpl.java:4302)
	at org.datanucleus.state.StateManagerImpl.replaceFields(StateManagerImpl.java:4327)
	at org.datanucleus.store.mongodb.MongoDBUtils$1.fetchFields(MongoDBUtils.java:796)
	at org.datanucleus.state.StateManagerImpl.loadFieldValues(StateManagerImpl.java:3719)
	at org.datanucleus.state.StateManagerImpl.initialiseForHollow(StateManagerImpl.java:383)
	at org.datanucleus.state.ObjectProviderFactoryImpl.newForHollow(ObjectProviderFactoryImpl.java:113)
	at org.datanucleus.ExecutionContextImpl.findObject(ExecutionContextImpl.java:3194)
	at org.datanucleus.store.mongodb.MongoDBUtils.getObjectUsingApplicationIdForDBObject(MongoDBUtils.java:791)
	at org.datanucleus.store.mongodb.MongoDBUtils.getPojoForDBObjectForCandidate(MongoDBUtils.java:753)
	at org.datanucleus.store.mongodb.query.LazyLoadQueryResult.getNextObject(LazyLoadQueryResult.java:324)
	at org.datanucleus.store.mongodb.query.LazyLoadQueryResult$QueryResultIterator.next(LazyLoadQueryResult.java:449)
	at de.mpg.ipp.codac.persistence.DataNucleusProvider.doGetObjects(DataNucleusProvider.java:362)
	... 30 more`

I'm testing against MongoDB 3.0.15. I'll provide a test case demonstrating the issue and attached 2 test documents for the test case.
[DN.zip](https://github.com/datanucleus/datanucleus-mongodb/files/1889855/DN.zip)

**Comment by nonstans** [comment]
I found the change responsible for my problem:

https://github.com/datanucleus/datanucleus-core/commit/5516fd66e169793460341389832c8f1c0f88e508#diff-6948127ae2011ff7ee0f90cf34cf3e23

`-                Object val = ClassUtils.getValueOfFieldByReflection(id, "className");
+                Object val = ClassUtils.getValueOfFieldByReflection(id, "targetClassName");`

**Comment by nonstans** [comment]
I added a workaround to the checked in test code.

**Comment by nonstans** [comment]
Updating documents with references fails. The reasons seems to be the same. The root class containing the relevant fields for the Identity cannot be found in org.datanucleus.store.mongodb.MongoDBUtils#getClassNameForIdentity.

`try
        {
            DB db = (DB)mconn.getConnection();

            StoreData sd = storeMgr.getStoreDataForClass(rootCmd.getFullClassName()); //not found here
            if (sd == null)
            {
                // Make sure schema exists, using this connection
                ((MongoDBStoreManager)storeMgr).manageClasses(new String[] {rootCmd.getFullClassName()}, ec.getClassLoaderResolver(), db);
                sd = storeMgr.getStoreDataForClass(rootCmd.getFullClassName()); //still not found
            }

            Set rootClassNames = new HashSet<String>();
            rootClassNames.add(rootCmd.getFullClassName());
            Table tbl = sd.getTable(); //NPE, because sd is null` 


`java.lang.NullPointerException
	at org.datanucleus.store.mongodb.MongoDBUtils.getClassNameForIdentity(MongoDBUtils.java:216)
	at org.datanucleus.store.mongodb.MongoDBStoreManager.getClassNameForObjectID(MongoDBStoreManager.java:190)
	at org.datanucleus.state.StateManagerImpl.loadFieldsFromDatastore(StateManagerImpl.java:1487)
	at org.datanucleus.state.StateManagerImpl.loadSpecifiedFields(StateManagerImpl.java:3747)
	at org.datanucleus.state.StateManagerImpl.loadField(StateManagerImpl.java:3764)
	at org.datanucleus.store.fieldmanager.AttachFieldManager.storeObjectField(AttachFieldManager.java:170)
	at org.datanucleus.state.StateManagerImpl.providedObjectField(StateManagerImpl.java:1823)
	at org.datanucleus.tests.users.UserGroup.dnProvideField(UserGroup.java)
	at org.datanucleus.tests.users.W7XDbNamedObject.dnProvideFields(W7XDbNamedObject.java)
	at org.datanucleus.state.StateManagerImpl.provideFields(StateManagerImpl.java:2510)
	at org.datanucleus.state.StateManagerImpl.internalAttachCopy(StateManagerImpl.java:5353)
	at org.datanucleus.state.StateManagerImpl.attachCopy(StateManagerImpl.java:5286)
	at org.datanucleus.state.StateManagerImpl.attachCopy(StateManagerImpl.java:126)
	at org.datanucleus.ExecutionContextImpl.attachObjectCopy(ExecutionContextImpl.java:2584)
	at org.datanucleus.ExecutionContextImpl.persistObjectInternal(ExecutionContextImpl.java:1942)
	at org.datanucleus.ExecutionContextImpl.persistObjectWork(ExecutionContextImpl.java:1868)
	at org.datanucleus.ExecutionContextImpl.persistObject(ExecutionContextImpl.java:1723)
	at org.datanucleus.api.jdo.JDOPersistenceManager.jdoMakePersistent(JDOPersistenceManager.java:712)
	at org.datanucleus.api.jdo.JDOPersistenceManager.makePersistent(JDOPersistenceManager.java:738)
	at org.datanucleus.tests.ResolveReferencesTest.testModifyUserGroup(ResolveReferencesTest.java:133)
.. `

**Comment by nonstans** [comment]
Just in case you missed it...I provided a test case:
org.datanucleus.tests.ResolveReferencesTest#testModifyUserGroup

**Comment by andyjefferson** [comment]
Firstly you can "provide" a testcase all you want but if it is not visible to any other person on this project, then it is of little value. No, there is NOTHING attached to this "issue", other than a couple of JSON files.

Secondly there is no resource here for looking at people's problems, and ALL DN tests pass for MongoDB just as they did in every previous release, so you're doing something that this project doesn't support, by definition. As people have been advised since 15 yrs ago, if there is no test in the DN tests for your situation then it is not in scope. Suggest that you continue your debugging.

FWIW ABSTRACT classes cannot have a TABLE in the database, when we only support COMPLETE_TABLE strategy, and that is the same in v5.0, and indeed in all other non-RDBMS plugins.

Good luck

**Comment by andyjefferson** [comment]
No testcase still, so closing, as per the template says when opening an issue. Issues can be reopened only with valid testcases attached

**Comment by nonstans** [comment]
Finally I found some time to provide a test case. Furthermore the issue is more clear to me now.
The problem seems to occur for classes that have the annotation @Cacheable("false") and inherit attributes from some abstract superclass.

`Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.995 sec <<< FAILURE! - in org.datanucleus.tests.ResolveReferencesTest
modifyNonCacheableObject[default](org.datanucleus.tests.ResolveReferencesTest)  Time elapsed: 0.404 sec  <<< ERROR!
java.lang.NullPointerException: null
        at org.datanucleus.store.mongodb.MongoDBUtils.getClassNameForIdentity(MongoDBUtils.java:216)
        at org.datanucleus.store.mongodb.MongoDBStoreManager.getClassNameForObjectID(MongoDBStoreManager.java:190)
        at org.datanucleus.state.StateManagerImpl.loadFieldsFromDatastore(StateManagerImpl.java:1499)
        at org.datanucleus.state.StateManagerImpl.loadSpecifiedFields(StateManagerImpl.java:3765)
        at org.datanucleus.state.StateManagerImpl.loadField(StateManagerImpl.java:3782)
        at org.datanucleus.store.fieldmanager.AttachFieldManager.storeObjectField(AttachFieldManager.java:170)
        at org.datanucleus.state.StateManagerImpl.providedObjectField(StateManagerImpl.java:1865)
        at org.datanucleus.tests.users.UserGroup.dnProvideField(UserGroup.java)
        at org.datanucleus.tests.users.W7XDbNamedObject.dnProvideFields(W7XDbNamedObject.java)
        at org.datanucleus.state.StateManagerImpl.provideFields(StateManagerImpl.java:2528)
        at org.datanucleus.state.StateManagerImpl.internalAttachCopy(StateManagerImpl.java:5371)
        at org.datanucleus.state.StateManagerImpl.attachCopy(StateManagerImpl.java:5304)
        at org.datanucleus.state.StateManagerImpl.attachCopy(StateManagerImpl.java:126)
        at org.datanucleus.ExecutionContextImpl.attachObjectCopy(ExecutionContextImpl.java:2584)
        at org.datanucleus.ExecutionContextImpl.persistObjectInternal(ExecutionContextImpl.java:1942)
        at org.datanucleus.ExecutionContextImpl.persistObjectWork(ExecutionContextImpl.java:1868)
        at org.datanucleus.ExecutionContextImpl.persistObject(ExecutionContextImpl.java:1723)
        at org.datanucleus.api.jdo.JDOPersistenceManager.jdoMakePersistent(JDOPersistenceManager.java:712)
        at org.datanucleus.api.jdo.JDOPersistenceManager.makePersistent(JDOPersistenceManager.java:738)
        at org.datanucleus.tests.ResolveReferencesTest.modifyNonCacheableObject(ResolveReferencesTest.java:75)


Results :

Tests in error:
  ResolveReferencesTest.modifyNonCacheableObject:75 » NullPointer
`

See test case here:
https://github.com/nonstans/tests/commit/7d62fc4508e1fa829a91d6fcd40b7c062424f77f#diff-54b6fd9580921e11353f9a464009990a

As I wrote here:
https://github.com/datanucleus/datanucleus-mongodb/issues/46#issuecomment-381577354
the problem vanishes if I allow to use metadata from abstract classes.
