### ISSUE TITLE
@Converter not working

### ISSUE THREAD

**Issue by cyberquarks** [datanucleus/datanucleus-mongodb#55]
With these classes:

```java
@PersistenceCapable
public class Hub implements Serializable {
    private String name;
    private List<Schedule> schedules;
}
```

And 

```java
@PersistenceCapable
@EmbeddedOnly
public class Schedule implements Serializable {
    private String day;
    @Convert(LocalTimeConverter.class)
    private String opens;
    @Convert(LocalTimeConverter.class)
    private String closes;
}
```

The converter does not work, the stored document should be a number/Long and not the String field value since there is a converter. The converter code can be found here: https://github.com/cyberquarks/test-jdo-converter/blob/master/src/main/java/mydomain/model/converter/LocalTimeConverter.java

Here's the test case: https://github.com/cyberquarks/test-jdo-converter
The issue affects the latest version of Datanucleus/Datanucleus JDO

**Comment by andyjefferson** [comment]
Converting a String to a Long is frankly a strange thing to do, @Convert is for allowing otherwise non-persistable things to be persisted by converting to an acceptable type. Clearly it could be possible to support such a thing with effort but I personally won't be doing so. You could contribute this if it is important to you

**Comment by cyberquarks** [comment]
@andyjefferson okay I will check the code, so at the surface now the problem is not with the core or JDO module but rather the mongodb database module? 

Yes, in fact is it strange thing, but there's a concrete use-case for this which is to query local time ranges (not date) 
So one could query for a LocalTime withing a range of LocalTime (hence _opens_, and _closes_ field)

And do, something like:
`SELECT FROM mydomain.Hub WHERE this.schedules.contains(sch) && (sch.day == :schDay && sch.opens <= :startTime && sch.closes >= :endTime)`

**Comment by cyberquarks** [comment]
@andyjefferson 

To further investigate the issue I create a very simple Converter:

```java
public class StringConverter implements AttributeConverter<String, String> {
    @Override
    public String convertToDatastore(String attributeValue) {
        return attributeValue;
    }

    @Override
    public String convertToAttribute(String datastoreValue) {
        return datastoreValue;
    }
}
```
Then placed breakpoints in both methods and exercised this through the DN API, the converter never gets called, does it mean `@Convert` does not work for Datanucleus MongoDB module or it really does not work at all for DataNucleus in general?

**Comment by andyjefferson** [comment]
I've already told you ... converters are supported for Object fields that are not the standard Java types (primitive wrappers, String etc). Just look at the code if you have a doubt / problem.

**Comment by cyberquarks** [comment]
@andyjefferson I managed to get the converter to work by this:

```java
public class LocalTimeConverter implements AttributeConverter<LocalTime, Long> {
    @Override
    public Long convertToDatastore(LocalTime attributeValue) {
        return attributeValue.toNanoOfDay();
    }
    @Override
    public LocalTime convertToAttribute(Long value) {
        LocalTime localTime = LocalTime.ofNanoOfDay(value);
        return localTime;
    }
}
```

But I also have found that `@Converter` does not work within query. Meaning to say, the generated Query did not pass through the converter.

**Comment by andyjefferson** [comment]
DataNucleus already provides many built-in type converters, one of which is https://github.com/datanucleus/datanucleus-core/blob/master/src/main/java/org/datanucleus/store/types/converters/LocalTimeLongConverter.java so just defining the DB type ought to be enough.

And what happens in a query depends totally on the query. Because a query is typically executed IN THE DATASTORE, the majority of queries would never allow any (java language) converter to be executed, because it doesn't exist in the datastore.

**Comment by cyberquarks** [comment]
@andyjefferson 

When the `@Converter` was omitted from the field (of type `LocalTime`) to make use of the built-in converter you get:

```
java.lang.IllegalArgumentException
	at java.sql.Time.valueOf(Time.java:110)
	at org.datanucleus.util.TypeConversionHelper.convertTo(TypeConversionHelper.java:1009)
	at org.datanucleus.store.mongodb.fieldmanager.FetchFieldManager.fetchNonEmbeddedObjectField(FetchFieldManager.java:808)
	at org.datanucleus.store.mongodb.fieldmanager.FetchFieldManager.fetchObjectField(FetchFieldManager.java:683)
	at org.datanucleus.state.StateManagerImpl.replacingObjectField(StateManagerImpl.java:1995)
```

**Comment by cyberquarks** [comment]
Furthermore, it gets saved like this:

```json
{
  "_id": {
    "$oid": "5fe7acf63f5f1cdec80e576c"
  },
  "name": "Hub1",
  "schedules": [
    {
      "opens": {
        "$date": "2020-12-26T23:00:00.000Z"
      },
      "day": "SATURDAY",
      "closes": {
        "$date": "2020-12-27T03:00:00.000Z"
      }
    },
    {
      "opens": {
        "$date": "2020-12-27T05:00:00.000Z"
      },
      "day": "SUNDAY",
      "closes": {
        "$date": "2020-12-27T15:00:00.000Z"
      }
    }
  ]
}
```

Meaning to say , even with fields 

```java
  private LocalTime opens;
  private LocalTime closes;
```

defined as `LocalTIme`, it get's auto-translated into a Date (which is incorrect)

**Comment by andyjefferson** [comment]
And you can conclude from that that you haven't defined to it the db type to save it as, but then the log would likely tell plenty, as would debug

**Comment by cyberquarks** [comment]
@andyjefferson 

I can see from https://sourcegraph.com/github.com/datanucleus/datanucleus-core@14e104d5409895e65046cf6c18715185c1bda576/-/blob/src/main/java/org/datanucleus/store/types/TypeManagerImpl.java#L1067:9

That `LocalTime` indeed resolves to `dn.localtime-sqltime` but how can it be modified?

**Comment by andyjefferson** [comment]
Jdbctype. And all of this is nothing to do with an issue about support for converters of basic types, so please use support mechanisms, not here
